[package]
name = "warp-token-from-header"
version = "0.1.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2024"

[dependencies]
async-graphql = { path = "../../.." }
async-graphql-warp = { path = "../../../integrations/warp" }
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.4", features = ["server", "websocket"] }
token = { path = "../../models/token" }
