[workspace]
members = [
    "models/starwars",
    "models/books",
    "models/files",

    "actix-web/token-from-header",
    "actix-web/subscription",
    "actix-web/upload",
    "actix-web/starwars",
    "actix-web/error-extensions",
    "actix-web/defer",

    "warp/starwars",
    "warp/subscription",
    "warp/token-from-header",

    "federation/federation-accounts",
    "federation/federation-products",
    "federation/federation-reviews",

    "tide/starwars",
    "tide/token-from-header",
    "tide/dataloader",
]
