[package]
name = "tide-starwars"
version = "0.1.1"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "../../.." }
async-graphql-tide = { path = "../../../integrations/tide" }
tide = "0.14"
async-std = "1.5.0"
starwars = { path = "../../models/starwars" }

[dev-dependencies]
serde_json = "1.0.51"
surf = "2.0.0-alpha.5"
