# For more information take a look at https://rocket.rs/guide/configuration/
[global.limits]
graphql = 131072

[debug]
address = "127.0.0.1"
port = 8000
keep_alive = 5
log_level = "normal"


[staging]
address = "0.0.0.0"
port = 8080
keep_alive = 5
log_level = "normal"


[release]
address = "0.0.0.0"
port = 8080
keep_alive = 5
log_level = "critical"
